### ISSUE TITLE
Music Resource Pack does not work

### ISSUE THREAD

**Issue by Noah765** [sf-inc/music_control#22] opened 2022-04-22 08:46 UTC
I made a custom medieval music resource pack (with songs from the internet) and it doesn't work for some reason I cannot figure out. I use quite a lot of mods, maybe the mod resounding has something to do with it. I get weird behaviour in general, such as I have to kill myself to be able to hear music. Here is my resource pack: https://drive.google.com/file/d/1BO0U6X-N6YY0BdlqleETCBxgc9g_8GzC/view (I hope the link works)

**Comment by charlyb01** [comment] 2022-05-01 14:16
I don't have much time to test but I will tell you when I do. The link works btw.
I've quickly checked it and it doesn't seem you made any mistake. I used it on my client and I was able to play one of your songs but others were not playing any sound. I'll update you when I know more about it later, but not very soon sadly

**Comment by TemporalDilation** [comment] 2022-11-21 13:57
I also have the same kind of issue. A music pack I put together doesn't work at all.

**Comment by charlyb01** [comment] 2023-02-20 20:38
Hello, I know this has been a while and I apologize! I'm not sure what causes the issue, but your music seem big. I have been told that Minecraft doesn't recognize music files that have a too big bitrate. I would recommend you to convert your music to ogg with Audacity, as I never encounter any issue with default parameters. But otherwise, you should try limiting the bitrate to 192kB/s

**Comment by charlyb01** [comment] 2024-04-04 15:27
Hello again, I know it's been a while and I'm sorry for that (again). I told you about the bitrate and it doesn't seem to be correct. I tried exporting your files with even bigger quality and it still worked. I don't know what is the cause of this but I suspect your converted your music with an online converter that exports with parameters incompatible with Minecraft. Exporting it back to ogg from Audacity makes all of your music work, no matter the settings I put. It is not related to my mod, closing the issue

**Closed by charlyb01** 2024-04-04 15:27 UTC
